# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66c5cd5f2bc9f2fefca2c3202d28364a2995644e8f7c0637b197e356a597a00181e0ae26aef50af5b12392171ed2bb75abab9501c998a04d34009120e46ebef

test:
  secret_key_base: 3ba8906591a422b5e78dee05796eb036e15f177830d2935ebb5ec2c944a4f4b33082b369f13852f2413733efcb1d1a4b3beac5acff4cb878e89e765f67d07204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
